[package]
name = "lassowrap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
windows = { version = "0.61", features = [
    "Win32_System_Threading",
    "Win32_Foundation",
] }
